---
functional:
  - Сайт должен работать под нагрузкой
  - Сайт должен отправлять пользователю электронное письмо с подтверждением, после того, как он успешно разместил заказ
  - Пользователь должен иметь возможность войти в систему, используя свое имя пользователя и пароль
non-functional:
  - Система должна быть доступна, когда это необходимо
  - Система должна работать на разных платформах с минимальными изменениями
  - Сайт должен быть совместим с другими системами
implicit:
  - На сайте должна быть возможность управления от имени администратора для редактирования категорий, цен, товаров
  - При оформлении заказа- пользователь должен оставлять свои контактные данные, телефон и почту
  - На сайте по умолчанию должна стоять языковая локализация, ориентировання на основного пользователя
  - Цены на товары должны быть в валюте, удобной основному пользователю
  - На сайте должна быть добавлена возможность оплаты
  - Сайт должен соответствовать законодательству "О персональных данных"
