---
functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - На сайте должна быть возможность управления от имени администратора для редактирования категорий, цен, товаров
  - При оформлении заказа- пользователь должен оставлять свои контактные данные, телефон и почту
  - На сайте по умолчанию должна стоять языковая локализация, ориентировання на основного пользователя
  - Цены на товары должны быть в валюте, удобной основному пользователю
  - На сайте должна быть добавлена возможность оплаты
  - Сайт должен соответствовать законодательству "О персональных данных"
