---
functional:
  - Сайт должен работать под нагрузкой
  - Сайт должен отправлять пользователю электронное письмо с подтверждением, после того, как он успешно разместил заказ
  - Пользователь должен иметь возможность войти в систему, используя свое имя пользователя и пароль
non-functional:
  - Система должна быть доступна, когда это необходимо
  - Система должна работать на разных платформах с минимальными изменениями
  - Сайт должен быть совместим с другими системами
implicit:
  - Должна быть возможность создать учётную запись пользователя
  - Должен соответствовать политике конфедициальности
  - Должна быть возможность добавить данные карты
